server:
  port: 8080

logging:
  level:
    org.springframework: info
spring:
  messages:
    basename: messages

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/admin/spring_uploaded_files
management:
  endpoints:
    web:
      exposure:
        include: "*"
