server:
  port: 8088

logging:
  level:
    org.springframework: debug
spring:
  messages:
    basename: messages

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/admin/spring_uploaded_files